import * as THREE from "three";

// Phase 2 of the 40x40-tile roadmap: replaces buildGroundTextures' baked
// color/rough canvases - generated by a synchronous per-pixel *JS* loop,
// the actual scaling bottleneck a large tile count runs into - with the
// same bake done on the *GPU* instead: a fragment shader (1:1 GLSL port of
// terrain.js's hash/noise2D/fbm/sampleType and
// VillagePathWalkScene.jsx's groundSample/paddyProximity math) rendered
// once to an offscreen render target per tile. Fully parallel across every
// pixel, so it's a fraction of a millisecond instead of seconds, and it
// never touches the main thread.
//
// This intentionally still produces *textures*, sampled normally via
// map/roughnessMap with the GPU's regular mipmap/bilinear filtering - an
// earlier version of this tried evaluating the same noise live, once per
// on-screen fragment, in the ground material's own shader instead of
// baking it. That aliased badly: the fine octaves (grain/pebble, scale
// ~18-36) are higher frequency than one screen pixel typically covers at
// normal zoom, and with no filtering that undersampling shows up as harsh
// salt-and-pepper noise instead of the soft grain a filtered texture gives
// "for free". Baking still avoids the scaling problem (the GPU bake is
// what happens once at tile-load time; sampling the resulting texture at
// render time is what already scaled fine before) - it's just baked by
// the GPU instead of blocking the main thread to do it pixel by pixel.
//
// Bump mapping is dropped rather than ported: its effect (bumpScale=0.015)
// was already barely perceptible, and it isn't worth a third baked
// texture. The real vertex-level terrain undulation still provides
// genuine large-scale shading variation.

const GLSL_NOISE = /* glsl */ `
  float gHash(vec2 p) {
    float s = sin(p.x * 127.1 + p.y * 311.7) * 43758.5453;
    return s - floor(s);
  }
  float gSmooth(float t) { return t * t * (3.0 - 2.0 * t); }
  float gNoise2D(vec2 p) {
    vec2 i = floor(p);
    vec2 f = p - i;
    float u = gSmooth(f.x);
    float v = gSmooth(f.y);
    float a = gHash(i);
    float b = gHash(i + vec2(1.0, 0.0));
    float c = gHash(i + vec2(0.0, 1.0));
    float d = gHash(i + vec2(1.0, 1.0));
    return a * (1.0 - u) * (1.0 - v) + b * u * (1.0 - v) + c * (1.0 - u) * v + d * u * v;
  }
  // octaves is always 2 or 4 here (matching terrain.js's sampleType call
  // sites) - a fixed 4-iteration loop with an early break covers both.
  float gFbm(vec2 p, int octaves) {
    float total = 0.0;
    float amp = 0.5;
    float freq = 1.0;
    float maxAmp = 0.0;
    for (int i = 0; i < 4; i++) {
      if (i >= octaves) break;
      total += gNoise2D(p * freq) * amp;
      maxAmp += amp;
      amp *= 0.5;
      freq *= 2.0;
    }
    return total / maxAmp;
  }
  float gSmoothstep(float e0, float e1, float x) {
    float t = clamp((x - e0) / (e1 - e0), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
  }
`;

// cfg: { clumpScale, grainScale, pebbleScale, colorLow: [r,g,b] 0-255,
// colorHigh: [r,g,b] 0-255, speckAmt, pebbleShadeAmt, roughLow, roughHigh }
// - the same shape as terrain.js's SOIL / VillagePathWalkScene.jsx's PATH.
function glslTerrainType(name, cfg) {
  const [lr, lg, lb] = cfg.colorLow.map((c) => c / 255);
  const [hr, hg, hb] = cfg.colorHigh.map((c) => c / 255);
  // speckAmt/pebbleShadeAmt are additive perturbations calibrated for the
  // JS version's 0-255 color range (e.g. 26 there is a ~10% wobble) - since
  // colorLow/High are normalized to 0-1 above, these need the same /255 to
  // stay proportionally the same size instead of blowing color values far
  // outside [0,1] and clamping to near-solid black/white speckle.
  const speckAmt = cfg.speckAmt / 255;
  const pebbleShadeAmt = cfg.pebbleShadeAmt / 255;
  return /* glsl */ `
    vec4 ${name}(vec2 wp) {
      float clump = gFbm(wp * ${cfg.clumpScale.toFixed(4)}, 4);
      float grain = gFbm(wp * ${cfg.grainScale.toFixed(4)} + 40.0, 2);
      float pebble = gFbm(wp * ${cfg.pebbleScale.toFixed(4)} + 80.0, 2);
      vec3 col = mix(vec3(${lr.toFixed(6)}, ${lg.toFixed(6)}, ${lb.toFixed(6)}),
                      vec3(${hr.toFixed(6)}, ${hg.toFixed(6)}, ${hb.toFixed(6)}), clump);
      float speck = (grain - 0.5) * ${speckAmt.toFixed(6)};
      col += vec3(speck, speck * 0.9, speck * 0.75);
      float pebbleShade = (pebble - 0.5) * ${pebbleShadeAmt.toFixed(6)};
      col += vec3(pebbleShade, pebbleShade * 0.9, pebbleShade * 0.8);
      float rough = ${cfg.roughHigh.toFixed(4)} - clump * ${(cfg.roughHigh - cfg.roughLow).toFixed(4)} - (grain - 0.5) * 0.08;
      return vec4(col, rough);
    }
  `;
}

// Shared core (both bake passes need the same gGroundSample), plus a main()
// that writes either the color or the roughness (broadcast to all three
// channels, so it works correctly as a roughnessMap regardless of which
// channel Three samples) depending on `mode`.
function buildBakeFragmentShader(opts, mode) {
  const {
    soil, path, pathCenterX, pathHalfWidth, pathEdgeSoft,
    paddyPlacements, paddyHalfW, paddyHalfD, paddyBankOuter,
    paddyFringeWidth, paddyFringeColor,
  } = opts;

  const paddyDistTerms = paddyPlacements
    .map(({ x, z }) => `
      {
        float ax = max(0.0, abs(wp.x - (${x.toFixed(4)})) - ${(paddyHalfW + paddyBankOuter).toFixed(4)});
        float az = max(0.0, abs(wp.y - (${z.toFixed(4)})) - ${(paddyHalfD + paddyBankOuter).toFixed(4)});
        float dist = length(vec2(ax, az));
        t = max(t, 1.0 - gSmoothstep(0.0, ${paddyFringeWidth.toFixed(4)}, dist));
      }
    `)
    .join("\n");

  const [fr, fg, fb] = paddyFringeColor.map((c) => c / 255);

  return /* glsl */ `
    varying vec2 vUv;
    uniform vec2 uWorldSize; // (worldW, worldD)
    uniform vec2 uCenter;    // (xCenter, zCenter)
    ${GLSL_NOISE}
    ${glslTerrainType("gSoil", soil)}
    ${glslTerrainType("gPath", path)}
    float gPaddyProximity(vec2 wp) {
      float t = 0.0;
      ${paddyDistTerms}
      return t;
    }
    vec4 gGroundSample(vec2 wp) {
      vec4 soilS = gSoil(wp);
      vec4 pathS = gPath(wp);
      float distFromPath = abs(wp.x - (${pathCenterX.toFixed(4)}));
      float t = 1.0 - gSmoothstep(${pathHalfWidth.toFixed(4)}, ${(pathHalfWidth + pathEdgeSoft).toFixed(4)}, distFromPath);
      vec3 col = mix(soilS.rgb, pathS.rgb, t);
      float rough = mix(soilS.a, pathS.a, t);
      float fringe = gPaddyProximity(wp);
      col = mix(col, vec3(${fr.toFixed(6)}, ${fg.toFixed(6)}, ${fb.toFixed(6)}), fringe);
      rough -= fringe * 0.15;
      return vec4(col, rough);
    }
    void main() {
      vec2 wp = (vUv - 0.5) * uWorldSize + uCenter;
      vec4 gs = gGroundSample(wp);
      ${mode === "color" ? "gl_FragColor = vec4(gs.rgb, 1.0);" : "gl_FragColor = vec4(gs.a, gs.a, gs.a, 1.0);"}
    }
  `;
}

const BAKE_VERTEX_SHADER = /* glsl */ `
  varying vec2 vUv;
  void main() {
    vUv = uv;
    gl_Position = vec4(position, 1.0);
  }
`;

let bakeScene = null;
let bakeCamera = null;
let bakeQuadGeo = null;
function getBakeRig() {
  if (!bakeScene) {
    bakeScene = new THREE.Scene();
    bakeCamera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    bakeQuadGeo = new THREE.PlaneGeometry(2, 2);
  }
  return { bakeScene, bakeCamera, bakeQuadGeo };
}

function bakeOnePass(renderer, texW, texH, worldW, worldD, xCenter, zCenter, opts, mode) {
  const { bakeScene, bakeCamera, bakeQuadGeo } = getBakeRig();
  const material = new THREE.ShaderMaterial({
    vertexShader: BAKE_VERTEX_SHADER,
    fragmentShader: buildBakeFragmentShader(opts, mode),
    // The sin()-based hash below is precision-sensitive by nature (large
    // sin() arguments); forcing highp here is cheap insurance against a
    // mediump default, even though the actual bug that first produced
    // harsh black/white noise here (hunted down empirically) turned out to
    // be a units mismatch in glslTerrainType, not a precision problem.
    precision: "highp",
    uniforms: {
      uWorldSize: { value: new THREE.Vector2(worldW, worldD) },
      uCenter: { value: new THREE.Vector2(xCenter, zCenter) },
    },
  });
  const quad = new THREE.Mesh(bakeQuadGeo, material);
  bakeScene.add(quad);

  const renderTarget = new THREE.WebGLRenderTarget(texW, texH, {
    type: THREE.UnsignedByteType,
    generateMipmaps: true,
    minFilter: THREE.LinearMipmapLinearFilter,
    magFilter: THREE.LinearFilter,
  });

  const prevTarget = renderer.getRenderTarget();
  renderer.setRenderTarget(renderTarget);
  renderer.render(bakeScene, bakeCamera);
  renderer.setRenderTarget(prevTarget);

  bakeScene.remove(quad);
  material.dispose();
  return renderTarget;
}

// Renders one GRID_SIZE x GRID_SIZE tile's color and roughness to two
// render targets on the GPU, once, synchronously - unlike the old CPU
// canvas loop this doesn't block the main thread in any way that matters
// (two small quad draws), so there's no async/await here despite
// "rendering" happening. Returns { colorTarget, roughTarget }; dispose()
// both (and their .texture) when the tile unloads.
export function bakeGroundTextures(renderer, texW, texH, worldW, worldD, xCenter, zCenter, opts) {
  const colorTarget = bakeOnePass(renderer, texW, texH, worldW, worldD, xCenter, zCenter, opts, "color");
  const roughTarget = bakeOnePass(renderer, texW, texH, worldW, worldD, xCenter, zCenter, opts, "rough");
  return { colorTarget, roughTarget };
}

export function buildGroundMaterial(colorTarget, roughTarget) {
  return new THREE.MeshStandardMaterial({
    map: colorTarget.texture,
    roughnessMap: roughTarget.texture,
    roughness: 1,
    metalness: 0.02,
  });
}
